### ISSUE TITLE
Issue parsing vasp poscar file

### ISSUE THREAD

**Issue by linnlii** [mfherbst/ASEconvert.jl#15]
I'm new to Julia and I'm trying to call the corresponding read_vasp python function in Julia. In Python, the io submodule is not directly exposed, so it is usually done by "from ase.io import vasp" or "from ase.io.vasp import read_vasp". How can I call the read_vasp function using the ASEconvert in Julia? I've tried directly calling ase.io.vasp.read_vasp(poscar_path), and it outputs the error "Python: AttributeError: module 'ase.io' has no attribute 'vasp'"

**Comment by mfherbst** [comment]
You could do the following:
```julia
using ASEconvert
using PythonCall

read_vasp = pyimport("ase.io.vasp").read_vasp
```

However, what I would recommend is to use the [AtomsIO](https://github.com/mfherbst/AtomsIO.jl) package instead, where this will be simply:

```julia
using AtomsIO
system = load_system("path/to/POSCAR")
```
which provides the data in AtomsBase-compatible format.

Hope this helps.

**Comment by linnlii** [comment]
I've tried both. For the first method you suggested, the output is a python object. Then I tried to convert it to the AtomsBase-compatible format by doing pyconvert(AbstractSystem, atoms_ase), and got an "ArgumentError: invalid Array dimensions".

For the second method, I also got the "ArgumentError: invalid Array dimensions".

However, if I convert the poscar into a cif file, then load_system function works fine.

**Comment by mfherbst** [comment]
I see. That sounds like a bug somewhere in the stack (likely in ASEconvert). Could you share the POSCAR file ?

**Comment by linnlii** [comment]
Si2
1.0
  -2.7343639999999998   -2.7343639999999998    0.0000000000000000
  -2.7343639999999998    0.0000000000000000   -2.7343639999999998
   0.0000000000000000   -2.7343639999999998   -2.7343639999999998
Si
2
direct
   0.7500000000000000    0.7500000000000000    0.7500000000000000 Si
   0.0000000000000000    0.0000000000000000    0.0000000000000000 Si

**Comment by linnlii** [comment]
[POSCAR.txt](https://github.com/mfherbst/ASEconvert.jl/files/12621510/POSCAR.txt)

Added a .txt extension to the file since the original file format is not supported.

**Comment by mfherbst** [comment]
Found the bug, the issue was something in our printing code, see https://github.com/JuliaMolSim/AtomsBase.jl/pull/82. The parsing seems to be correct though.

**Comment by mfherbst** [comment]
I released a new AtomsBase, so it should be working once that's in the General package registry.
